[2024-06-14T05:53:01.466+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T05:53:01.517+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2024-06-14T05:52:59.478774+00:00 [queued]>
[2024-06-14T05:53:01.529+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2024-06-14T05:52:59.478774+00:00 [queued]>
[2024-06-14T05:53:01.530+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-14T05:53:01.552+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2024-06-14 05:52:59.478774+00:00
[2024-06-14T05:53:01.563+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'manual__2024-06-14T05:52:59.478774+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpio4c907y']
[2024-06-14T05:53:01.565+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask python_job
[2024-06-14T05:53:01.567+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=554) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-14T05:53:01.568+0000] {standard_task_runner.py:63} INFO - Started process 555 to run task
[2024-06-14T05:53:01.621+0000] {task_command.py:426} INFO - Running <TaskInstance: sparking_flow.python_job manual__2024-06-14T05:52:59.478774+00:00 [running]> on host cf5928e4c8ca
[2024-06-14T05:53:01.724+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T05:52:59.478774+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T05:52:59.478774+00:00'
[2024-06-14T05:53:01.725+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T05:53:01.748+0000] {spark_submit.py:204} INFO - Could not load connection string spark-conn, defaulting to yarn
[2024-06-14T05:53:01.749+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py
[2024-06-14T05:53:01.823+0000] {spark_submit.py:488} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T05:53:03.166+0000] {spark_submit.py:488} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-06-14T05:53:03.167+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-06-14T05:53:03.168+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-06-14T05:53:03.168+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-06-14T05:53:03.169+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-06-14T05:53:03.169+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-06-14T05:53:03.170+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-06-14T05:53:03.171+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-06-14T05:53:03.172+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-06-14T05:53:03.172+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-06-14T05:53:03.173+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-06-14T05:53:03.183+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T05:53:03.194+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.
[2024-06-14T05:53:03.199+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, run_id=manual__2024-06-14T05:52:59.478774+00:00, execution_date=20240614T055259, start_date=20240614T055301, end_date=20240614T055303
[2024-06-14T05:53:03.212+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task python_job (Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.; 555)
[2024-06-14T05:53:03.230+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T05:53:03.256+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T05:53:03.265+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
